### ISSUE TITLE
需求分析与原型图的修改建议

### ISSUE THREAD

**Issue by zzcypc** [FeinZee/data-visualization-internship#1]
# 第一版需求分析与原型图的修改建议
## 总体评价
能在半天时间内写好一份需求分析，并画出一份精美的原型图，让我感到了惊喜～可以看出你的认真与细致，这是个很好的开端，望继续保持～
虽然时钟图方案很有创意，但是它并不适合用来展示对比数据，效果不如折线图直观。原型图还需要再补充交互上的一些细节。
## 修改建议
1. 只需要多日趋势对比图（原型图中的C图表）就可以了，不需要对单日数据进行对比。
2. 在折线图下方再加一个表格，用来展示每日各个平台的uv、pv数据。表格底部需要显示汇总数据和日均数据。（以下图为例）
![image](https://user-images.githubusercontent.com/18070429/90131491-d23ce980-dd9e-11ea-853a-ac1719cbdc0a.png)
3. 补充日期选择器的交互细节，例如：用户如何修改日期，日期发生变化之后是否需要点击按钮才能触发图表更新。（可参考https://eplus.360.cn/vue/date-picker “选择日期范围”）
4. 考虑页面初始情况，当数据请求尚未返回时，页面如何呈现才能不影响用户体验。
5. 考虑数据返回异常的情况，页面如何展示，如何提示用户。
## 下个阶段目标
1. 完善需求分析和原型图
2. 设计数据库表结构

**Comment by zzcypc** [comment]
# 第二版需求分析与原型图的修改建议
## 修改建议
1. 在数据库表结构设计部分，由于自增id是正整数，而SMALLINT能够表示的数字范围是(-32 768，32 767)，其中一半空间是用来表示负数，无法利用，建议改为无符号类型SMALLINT UNSIGNED，其能表示的范围是(0，65 535)。pv和uv字段也都是正数，所以也建议使用无符号类型。
## 下个阶段目标
### 1. 对项目进行概要设计
- 明确整个项目需要实现的功能，对项目进行子模块划分（前端模块划分，后端模块划分）
- 可以采用流程图，将系统的各个步骤表示出来
- 定义前后端交互接口，编写接口文档和mock数据
### 2. 在概要设计的基础上进行详细设计
- 对各个模块的内部逻辑进行设计
### 3. 学习使用Think.js、Vue.js
- 可以尝试写一些demo，通过运用能够更快地掌握技术

**Comment by FeinZee** [comment]
已将id和pv、uv字段修改为SMALLINT UNSIGNED。
