### ISSUE TITLE
概要设计的修改建议

### ISSUE THREAD

**Issue by zzcypc** [FeinZee/data-visualization-internship#2]
### 请求接口格式
- 建议以表格或者列表的形式列出请求接口是需要携带的参数，标明每个字段的数据类型是什么，是否必填。RegExp显然不是读者能够理解的格式。
### 接口返回格式
- 数据返回格式一般由三部分组成：errCode（接口定义的错误码）、errMsg（接口错误时的提示信息）、data（返回的数据）。建议补充完善接口返回的基本结构，制定统一的错误码。
- 建议以表格或者列表的形式对请求返回数据中的各个字段加以说明。
- 建议添加数据返回的例子。
- 接口文档的书写可以参考wiki中的[接口文档示例](https://github.com/FeinZee/data-visualization-internship/wiki/%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3%E7%A4%BA%E4%BE%8B)

**Comment by FeinZee** [comment]
已修改文档中的接口部分

**Comment by zzcypc** [comment]
## 接口文档修改建议
1. 请求数据格式的表格建议再改一下。数据类型建议使用约定俗成的类型来描述。

| 参数名    | 必选 | 数据类型 | 说明                 | 示例       |
| :-------- | ---- | -------- | -------------------- | ---------- |
| startDate | 是   | String   | 开始日期(格式：YYYY-MM-DD) | 2020-08-01 |
| endDate   | 是   | String   | 结束日期(格式：YYYY-MM-DD) | 2020-08-07 |

数据类型用 `Date` 也可以。

2. 响应示例中，可以把 <code>\`\`\`json</code> 改为 <code>\`\`\`js</code> 或者 <code>\`\`\`</code>，也可以把json里的每个key都用双引号包起来，这样就不会出现红色的底色了。

3. 响应数据表格也应该加上各个字段的数据类型。

**Comment by FeinZee** [comment]
已修改。
